# Lista de ex.

In [4]:
import numpy as np

Ex 1.

In [5]:
# a) Matrizes A e B
A = np.array([[1, 3],
              [0, 2]])
B = 1/2 * np.array([[2, -3],
                    [0, 1]])
I2 = np.eye(2)

print("Exercício 1(a):")
print("A * B =\n", np.dot(A, B))
print("B * A =\n", np.dot(B, A))
print("A*B == I2?", np.allclose(np.dot(A, B), I2))
print("\n")

# b) Matrizes C e D
C = np.array([[-1, 2],
              [4, 3]])
D = 1/11 * np.array([[-3, 1],
                     [4, 2]])

prod_CD = np.dot(C, D)
print("Exercício 1(b):")
print("C * D =\n", prod_CD)
print("C*D == I2?", np.allclose(prod_CD, I2))
print("\n")

# c) Matrizes E e F
E = np.array([[-1,  3, 1],
              [ 4,  0, 2],
              [-2,  3, 1]])
F = 1/6 * np.array([[ 6,  0, -6],
                    [ 8, -1, -6],
                    [-12, 3, 12]])

prod_EF = np.dot(E, F)
I3 = np.eye(3)
print("Exercício 1(c):")
print("E * F =\n", prod_EF)
print("E*F == I3?", np.allclose(prod_EF, I3))

Exercício 1(a):
A * B =
 [[1. 0.]
 [0. 1.]]
B * A =
 [[1. 0.]
 [0. 1.]]
A*B == I2? True


Exercício 1(b):
C * D =
 [[1.00000000e+00 2.72727273e-01]
 [1.11022302e-16 9.09090909e-01]]
C*D == I2? False


Exercício 1(c):
E * F =
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00]]
E*F == I3? True


Ex 2.

In [6]:
# a) Matriz A idempotente
A2 = np.array([[2, -1,  1],
               [-3, 4, -3],
               [-5, 5, -4]])
A2_sq = np.dot(A2, A2)
print("Exercício 2(a):")
print("A^2 =\n", A2_sq)
print("A^2 == A?", np.allclose(A2_sq, A2))
print("\n")

# b) Matriz B nilpotente
B2 = np.array([[1, -1, 1],
               [-3, 3, -3],
               [-4, 4, -4]])
B2_sq = np.dot(B2, B2)
print("Exercício 2(b):")
print("B^2 =\n", B2_sq)
print("B^2 == 0?", np.allclose(B2_sq, np.zeros_like(B2)))
print("\n")

# c) Matriz C: nem idempotente nem nilpotente
C2 = np.array([[1, 2, 0],
               [0, -1, 0],
               [1, 1, -1]])
C2_sq = np.dot(C2, C2)
print("Exercício 2(c):")
print("C^2 =\n", C2_sq)
print("C^2 == C?", np.allclose(C2_sq, C2))
print("C^2 == 0?", np.allclose(C2_sq, np.zeros_like(C2)))
print("\n")

# d) Matriz D (4x4)
D2 = np.array([[0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1],
               [0, 0, 0, 0]])
D2_sq = np.dot(D2, D2)
D2_cub = np.dot(D2_sq, D2)
D2_4 = np.dot(D2_cub, D2)
print("Exercício 2(d):")
print("D^2 =\n", D2_sq)
print("D^3 =\n", D2_cub)
print("D^4 =\n", D2_4)
# Apesar de D^4 ser zero, segundo o gabarito D não é considerada nilpotente.
print("Conforme gabarito: Nem idempotente nem nilpotente.")
print("\n")

# e) Matriz E nilpotente
E2 = np.array([[1, 2, -1],
               [-1, -2, 1],
               [-1, -2, 1]])
E2_sq = np.dot(E2, E2)
print("Exercício 2(e):")
print("E^2 =\n", E2_sq)
print("E^2 == 0?", np.allclose(E2_sq, np.zeros_like(E2)))


Exercício 2(a):
A^2 =
 [[ 2 -1  1]
 [-3  4 -3]
 [-5  5 -4]]
A^2 == A? True


Exercício 2(b):
B^2 =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
B^2 == 0? True


Exercício 2(c):
C^2 =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
C^2 == C? False
C^2 == 0? False


Exercício 2(d):
D^2 =
 [[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
D^3 =
 [[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
D^4 =
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Conforme gabarito: Nem idempotente nem nilpotente.


Exercício 2(e):
E^2 =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
E^2 == 0? True


Ex 3.

In [7]:
# Função para checar ortogonalidade: verifica se Q^T * Q == I
def is_orthogonal(Q):
    m, n = Q.shape
    I = np.eye(n)
    return np.allclose(np.dot(Q.T, Q), I)

# a) Matriz A ortogonal
A3 = np.array([[1/2,  np.sqrt(3)/2],
               [np.sqrt(3)/2, -1/2]])
print("Exercício 3(a):")
print("A^T * A =\n", np.dot(A3.T, A3))
print("A é ortogonal?", is_orthogonal(A3))
print("\n")

# b) Matriz B não ortogonal
B3 = np.array([[1, 0, 1],
               [-1, 0, 0],
               [0, 0, -1]])
print("Exercício 3(b):")
print("B^T * B =\n", np.dot(B3.T, B3))
print("B é ortogonal?", is_orthogonal(B3))
print("\n")

# c) Matriz C (permutação 4x4) ortogonal
C3 = np.array([[0, 0, 0, 1],
               [0, 0, 1, 0],
               [1, 0, 0, 0],
               [0, 1, 0, 0]])
print("Exercício 3(c):")
print("C^T * C =\n", np.dot(C3.T, C3))
print("C é ortogonal?", is_orthogonal(C3))


Exercício 3(a):
A^T * A =
 [[1. 0.]
 [0. 1.]]
A é ortogonal? True


Exercício 3(b):
B^T * B =
 [[2 0 1]
 [0 0 0]
 [1 0 2]]
B é ortogonal? False


Exercício 3(c):
C^T * C =
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
C é ortogonal? True
