In [19]:
import numpy as np
import sympy as sp

# Ex 1



In [20]:
AB = np.array([[-1, 0],
               [ 2, 1]])

AC = np.array([[2,  1],
               [0, -1]])

A_B_plus_C = AB + AC
print("A(B+C) =\n", A_B_plus_C)

A_BAC = AB.dot(AC)
print("\nA(BAC) =\n", AC)


A(B+C) =
 [[1 1]
 [2 0]]

A(BAC) =
 [[ 2  1]
 [ 0 -1]]


# Ex 2

In [21]:
alpha = 1
X = np.array([[1, 1],
              [alpha, 1]])

X_squared = np.dot(X, X)
X_2 = 2 * X

print("X =\n", X)
print("X^2 =\n", X_squared)
print("2X =\n", X_2)

print("X^2 == 2X? ", np.allclose(X_squared, X_2))


X =
 [[1 1]
 [1 1]]
X^2 =
 [[2 2]
 [2 2]]
2X =
 [[2 2]
 [2 2]]
X^2 == 2X?  True


#Ex 3

In [22]:
# Definindo as incógnitas
x, y, z, w = sp.symbols('x y z w', real=True)

# Matriz da esquerda: 3 vezes cada variável
M_left = sp.Matrix([[3*x, 3*y],
                    [3*z, 3*w]])

# Soma das duas matrizes do lado direito:
# Primeira matriz:
M1 = sp.Matrix([[x, 6],
                [-1, 2*w]])
# Segunda matriz:
M2 = sp.Matrix([[4, x+y],
                [z+w, 3]])
M_right = M1 + M2

# Equacionando as matrizes elemento a elemento
eqs = [sp.Eq(M_left[i, j], M_right[i, j]) for i in range(2) for j in range(2)]
sol = sp.solve(eqs, (x, y, z, w), dict=True)

print("Solução:", sol)
# Espera-se: x = 2, y = 4, z = 1, w = 3.

Solução: [{w: 3, x: 2, y: 4, z: 1}]


# Ex 4

In [28]:
x, y, z = sp.symbols('x y z', real=True)

M1 = sp.Matrix([[x, y, z],
                [2, -1, 3],
                [4,  1, -8]])
M2 = sp.Matrix([[3,  2,  1],
                [-2, 2, -3],
                [-4, -1, 9]])

M_sum = M1 + M2
I3 = sp.eye(3)

eqs = [sp.Eq(M_sum[i, j], I3[i, j]) for i in range(3) for j in range(3)]
sol = sp.solve(eqs, (x, y, z), dict=True)

print("Resolução: (obtendo z = -1):", sol)

Resolução: (obtendo z = -1): [{x: -2, y: -2, z: -1}]


# Ex 5

In [24]:
M = np.array([[3, 2],
              [-1, -4]])

A = -M
print("A =\n", A)

A =
 [[-3 -2]
 [ 1  4]]


# Ex 6

In [25]:
I2 = np.eye(2)
M = np.array([[1, 2],
              [1, 3]])

X = I2 - M
print("X =\n", X)

X =
 [[ 0. -2.]
 [-1. -2.]]


# Ex 7

In [26]:
a, b = sp.symbols('a b', real=True)

eq1 = sp.Eq(1 + a*b, 11)  # (1,1)
eq2 = sp.Eq(3*a, 6)       # (1,2)
eq3 = sp.Eq(3*b, 15)      # (2,1)
sol = sp.solve([eq1, eq2, eq3], (a, b), dict=True)

print("\nExercício 7:")
print("Solução:", sol)


Exercício 7:
Solução: [{a: 2, b: 5}]


# Ex 8

In [29]:
x, y = sp.symbols('x y', real=True)

A = sp.Matrix([[1, 0],
               [1, 2]])
B = sp.Matrix([[7, x],
               [y, 0]])

AB = A * B
BA = B * A

eqs = [sp.Eq(AB[i, j], BA[i, j]) for i in range(2) for j in range(2)]
sol = sp.solve(eqs, (x, y), dict=True)

print("Solução:", sol)

Solução: [{x: 0, y: -7}]
